#ifndef __GUI_H
#define __GUI_H

#define BUTTON_SIZE		32

typedef enum E_NGWTYPE
{
	TYPE_DESKTOP,
	TYPE_FRAME,
	TYPE_WINDOW,
	TYPE_BUTTON,
	TYPE_TEXTBOX,
	TYPE_TOOLBAR,
	TYPE_NONE
}NGWTYPE;

typedef enum E_NGWSTATUS
{
	NSTATUS_DEAD,
	NSTATUS_IDLE,
	NSTATUS_MOUSEOVER,
	NSTATUS_MOUSEDOWN,
	NSTATUS_MOUSEHOLD,
	NSTATUS_MOUSEUP,
	NSTATUS_KEYDOWN,
	NSTATUS_KEYHOLD,
	NSTATUS_KEYUP,
	NSTATUS_VALIDATE,
	NSTATUS_CANCEL	
}NGWSTATUS;

/* API PUBLIC DECLARATIONS */
void NGTick(void);
void NGDraw(void);
void NGInit(void);
void NGDeinit(void);

extern t_glyph FONTSET[256];
extern TILESET CURSOR;
extern char *S_NGWTYPE[TYPE_NONE];
//* GUI MACROS *//

#endif
