#ifndef __MAPIC_H
#define __MAPIC_H


enum E_TOOLBARBUTTONS
{
	TOOLBAR_NEW,
	TOOLBAR_OPEN,
	TOOLBAR_SAVE,
	TOOLBAR_COMPILE,
	TOOLBAR_UNDO,
	TOOLBAR_REDO,
	TOOLBAR_CUT,
	TOOLBAR_COPY,
	TOOLBAR_PASTE,
	TOOLBAR_SHOWGRID,
	TOOLBAR_GRID,
	TOOLBAR_ZOOM,
	TOOLBAR_SELECT,
	TOOLBAR_PENCIL,
	TOOLBAR_LINE,
	TOOLBAR_RECT,
	TOOLBAR_FILL,
	TOOLBAR_ERASE,
	TOOLBAR_PROPERTIES,
	TOOLBAR_SHOW0,
	TOOLBAR_SHOW1,
	TOOLBAR_SHOW2,
	TOOLBAR_SHOW3,
	TOOLBAR_SHOWMESH,
	TOOLBAR_SHOWSPRICT,
	TOOLBAR_EDIT0,
	TOOLBAR_EDIT1,
	TOOLBAR_EDIT2,
	TOOLBAR_EDIT3,
	TOOLBAR_EDITMESH,
	TOOLBAR_EDITSPRICT,
	TOOLBAR_ROTATEL,
	TOOLBAR_ROTATER,
	TOOLBAR_FLIPH,
	TOOLBAR_FLIPV,
	TOOLBAR_FULLSCREEN,
	TOOLBAR_MAX
};


/* Custom declarations (MAPIC)*/
void DATASwitch(void);
void MapicTick(void);
void MapicInit(void);
void MapicDeinit(void);

extern WIDGET PROFILE_WINDOW;
extern WIDGET PROFILE_FRAME;
extern WIDGET MAP_FRAME;
extern WIDGET MAP_WINDOW;
extern WIDGET TILES_FRAME;
extern WIDGET SPRITE_FRAME;

#endif
